### ISSUE TITLE
Use `unittest.mock` if it is available

### ISSUE THREAD

**Issue by major** [googleapis/python-api-core#207]
#### Environment details

  - OS type and version: Fedora 34
  - Python version: `Python 3.9.5`
  - pip version: `pip 21.1.2`
  - `google-api-core` version: `1.3.0`

Using the `mock` module for recent versions of Python is deprecated. If the built-in `unittest.mock` is available for testing, that should be used instead.

**Comment by tseaver** [comment]
Superseded by #210.
