### ISSUE TITLE
Documentation for  "projectid" required when creating client using explicit credentials  

### ISSUE THREAD

**Issue by HemangChothani** [googleapis/python-api-core#21]
Reference issue: https://github.com/googleapis/python-storage/issues/93

When user pass a explicit credential at the time of client creation, they forgot to pass `project_id`.
They were unable to find documentation regarding that. even example in documentation specify only credentials to pass like `client = Client(credentials=credentials)`.
     
Here is the documentation of  [explicit credentials](https://googleapis.dev/python/google-api-core/latest/auth.html#explicit-credentials).
/cc @crwilcox @busunkim96

**Comment by busunkim96** [comment]
Storage uses google-cloud-core rather than google-api-core. https://googleapis.dev/python/google-cloud-core/latest/config.html explains how the `project_id` is set. Perhaps it would be better to update the storage documentation on client construction with the same information?

**Comment by HemangChothani** [comment]
Filed FR in goole-cloud-core, so closing the issue.
