### ISSUE TITLE
Dependency of packaging is no longer needed

### ISSUE THREAD

**Issue by allenhsu** [googleapis/python-api-core#215]
We use fpm to create in-house debs for all 3rd party libs, so we always check dependencies of 3rd party libs carefully. When doing the checks for `python-api-core`, we noticed that although `packaging` is included in `setup.py`, it's no longer used in the code base. I believe it can be safely removed. Not an issue, just a notice.

**Comment by parthea** [comment]
Hi @allenhsu,

Thank you for finding this! I agree we should remove it from `setup.py` and `testing/constraints-3.6.txt` . PRs are welcome!

**Comment by tseaver** [comment]
@parthea I don't think this can be a P1:  no user is broken by this.  In fact, I would mark it `type: cleanup` with no priority.

We also need to ensure that Owlbot wouldn't be restoring `packaging` anywhere.
