### ISSUE TITLE
Noxfile is not updated with Sphinx version pin

### ISSUE THREAD

**Issue by dandhlee** [googleapis/python-api-core#219]
is there a plan to use templated `noxfile.py` for this repo? If so, please help make it use the templated version, otherwise I'll manually update the noxfile content.

**Comment by dandhlee** [comment]
Not quite yet fixed as per Tres' comment in #224.

**Comment by tseaver** [comment]
`noxfile.py` in this repo differs from the templated version on several counts:

- It doesn't exclude `docfx` from the default session list.
- It has a `pytypes` session.
- It does *not* have a `system` session.
- It has an additional `unit_grpc_gcp` session which runs unit tests with `grpcio-gcp` installed.
- It uses `flake8-import-order` in its lint session.

**Comment by dandhlee** [comment]
I see. It sounds like `noxfile.py` file in this repo has a lot more stuff that needs to stay, if that's the case I'm happy to come back and manually update when needed for docfx. However, for other parts of `noxfile.py`, is there a way we're keeping things up to date with the template?

**Comment by tseaver** [comment]
>  is there a way we're keeping things up to date with the template?

Nope.  The pain threshhold for re-injecting the needed changes using `s.replace()` is pretty high, especially because the template gets changed for "arbitrary" reasons, which tends to break such replacements, proportionally to their number / complexity.

**Comment by dandhlee** [comment]
For that much stuff we need to add for this repo, it does seem fairly obnoxious to be adding multiple lines of `s.replace()`, I think it's fine to move on with just manually updating `noxfile.py` on this repo then 👍 

Thank you!
