### ISSUE TITLE
Field mask helper ignores optional fields explicitly set to default values

### ISSUE THREAD

**Issue by BenRKarl** [googleapis/python-api-core#232]
#### Environment details

  - OS type and version: glinux
  - Python version: `3.7.0`
  - pip version: `10.0.1`
  - `google-api-core` version: `1.31.0`

#### Steps to reproduce

Run the below code example.

#### Code example

```python
import proto
from google.api_core.protobuf_helpers import field_mask

class TestMessage(proto.Message):
    description = proto.Field(proto.STRING, number=1, optional=True)
    optimization_score = proto.Field(proto.INT64, number=2, optional=True)

test = TestMessage()

# Possibly related to Issue #230. When an optional field is explicitly set to its default value,
# i.e. empty string or zero, the field mask helper does not recognize that it's been set.
# Users must manually add the field path in these cases. 
test.description = ""
test.optimization_score = 0

fm = field_mask(None, test._pb)

assert fm.paths == ["description", "optimization_score"]
```

#### Stack trace
```
Traceback (most recent call last):
  File "meow.py", line 15, in <module>
    assert fm.paths == ["description", "optimization_score"]
AssertionError
```

**Comment by busunkim96** [comment]
From reading https://github.com/protocolbuffers/protobuf/blob/master/docs/field_presence.md, it looks like there is  support for field presence in `protobuf >3.12.0`. _Without_ that feature I don't think there is a way to distinguish a explicitly set value that is the same as the default.

We've required `>=3.12.0` for a while now (see https://github.com/googleapis/python-api-core/commit/1ba609592968c9d828449b89a3ade3bcaf5edd7f) so the version requirement is not a blocker.

However the doc says the field presence support is "experimental" so I'm not sure we should use it (in the spirit of stable libraries only depending on other stable interfaces). 

CC @software-dov

**Comment by parthea** [comment]
This appears to be the same as #230. See the response [here](https://github.com/googleapis/python-api-core/issues/230#issuecomment-915400893). I'm going to close this issue based on [this response](https://github.com/googleapis/python-api-core/issues/230#issuecomment-915400893) but please feel free to re-open it with more information.
