### ISSUE TITLE
Some libraries implicitly depend on `pytz` in google-api-core

### ISSUE THREAD

**Issue by busunkim96** [googleapis/python-api-core#250]
https://github.com/search?l=Python&p=2&q=org%3Agoogleapis+pytz+NOT+samples+NOT+tests&type=Code

pytz was dropped in https://github.com/googleapis/python-api-core/commit/a30f004e74f709d46e905dd819c71f43354e9ac9 to resolve https://github.com/googleapis/python-api-core/issues/73 (for the upcoming 2.0.0 release)

PR List:

https://github.com/googleapis/python-pubsub/pull/472
https://github.com/googleapis/python-bigquery/pull/875
https://github.com/googleapis/python-ndb/pull/707
https://github.com/googleapis/python-runtimeconfig/pull/78
https://github.com/googleapis/python-firestore/pull/422/ (optional)

**Comment by busunkim96** [comment]
All linked PRs have been merged.

**Comment by Gatsby-Lee** [comment]
@busunkim96  when are you going to deploy this change?
