### ISSUE TITLE
Do not throw error on empty LRO response

### ISSUE THREAD

**Issue by TrucHLe** [googleapis/python-api-core#257]
[operation.py](https://github.com/googleapis/python-api-core/blob/master/google/api_core/operation.py) throws an error if an LRO finishes but returns an empty response (the error message that it throws is "Unexpected state: Long-running operation had neither response nor error set"). However some APIs, such as Contact Center Insights, end LRO without setting either result or error (but set `done: true`). For example, please see [`ExportInsightsDataResponse`](https://cloud.google.com/contact-center/insights/docs/reference/rpc/google.cloud.contactcenterinsights.v1#exportinsightsdataresponse) which is an empty response that is returned after the `ExportInsightsData` LRO is complete.

We should update [operation.py](https://github.com/googleapis/python-api-core/blob/master/google/api_core/operation.py) to return an empty response instead of an error when it encounters an empty LRO. For reference, we found a similar issue in the NodeJS operation library and it was fixed [here](https://github.com/googleapis/gax-nodejs/pull/1087).

**Comment by busunkim96** [comment]
Hi @TrucHLe, 

I've opened a PR I believe will resolve the issue in #258. If you want to try it locally you can install it straight from the branch:

`pip install git+https://github.com/googleapis/python-api-core.git@fix-empty-LROs`

Thank you for providing a link to the NodeJS PR (and linking your sample PR)! Both were super helpful for understanding the issue. 😄
