### ISSUE TITLE
setuptools 60.0.0 breaking change

### ISSUE THREAD

**Issue by vpipkt** [googleapis/python-api-core#325]
install_requires should avoid `setuptools>=60` as it results in (apparently) a ModuleNotFound error. We encountered this in GitHub actions calls to `gcloud` tools.

#### Environment details

  - OS type and version: Ubuntu (Github Actions [ubuntu 2004](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md))
  - Python version: 3.7.12
  - `pip` version:  20.0.2
  - `google-api-core`  2.3.2
  - `setuptools` 60.0.0

#### Steps to reproduce

  1. pip install `google-api-core` with eager upgrade strategy
  2. make call to gcloud 

#### Code example

```bash
$ pip install --upgrade --upgrade-strategy eager  "google-api-python-client>=1.0.0"
$ gcloud container images list-tags
ERROR: gcloud failed to load (gcloud.container.images.list_tags): Problem loading gcloud.container.images.list_tags: No module named 'setuptools._distutils'.

# then try
$ pip install --upgrade --upgrade-strategy eager  "setuptools<60" "google-api-python-client>=1.0.0"
$ gcloud container images list-tags
ERROR: (gcloud.container.images.list-tags) argument IMAGE_NAME: Must be specified.
# This is the expected result .... 
```

####  CLI output in failure case
```
ERROR: gcloud failed to load (gcloud.container.images.list_tags): Problem loading gcloud.container.images.list_tags: No module named 'setuptools._distutils'.

This usually indicates corruption in your gcloud installation or problems with your Python interpreter.

Please verify that the following is the path to a working Python 2.7 or 3.5+ executable:
    /Users/jason.brown/.virtualenvs/dgx/bin/python3
If it is not, please set the CLOUDSDK_PYTHON environment variable to point to a working Python 2.7 or 3.5+ executable.

If you are still experiencing problems, please run the following command to reinstall:
    $ gcloud components reinstall

If that command fails, please reinstall the Cloud SDK using the instructions here:
    https://cloud.google.com/sdk/

```

**Comment by parthea** [comment]
Hi @vpipkt,

Thanks for reporting this issue. I've reached out to the gcloud sdk team. I'll update this issue once I hear back. Googlers see b/211562528.

**Comment by 0-wiz-0** [comment]
On the same topic: `setup.py` has setuptools in its dependencies, but I don't see how it's used in the code (there is no `import setuptools`). Should this really be there?

**Comment by parthea** [comment]
b/211562528 has been resolved. I'll keep this issue open until a new release is published and [docs](https://cloud.google.com/sdk/docs/release-notes) are updated.

**Comment by parthea** [comment]
I'm going to bump this to P2 as there is a workaround.

**Comment by parthea** [comment]
A new version of the gcloud SDK [368.0.0](https://cloud.google.com/sdk/docs/release-notes#36800_2022-01-11) was published yesterday which should fix this issue. Please feel free to re-open this issue if the new version of gcloud SDK doesn't resolve the issue.
