### ISSUE TITLE
Remove unused setuptools runtime dependency

### ISSUE THREAD

**Issue by EpicWink** [googleapis/python-api-core#338]
### Problem
Specifically for my use-case, I'm trying to remove `setuptools` from my application dependencies (so I can use [`pip-tools`](https://pypi.org/project/pip-tools/1.8.0/) with [`pip install --no-deps`](https://pip.pypa.io/en/stable/cli/pip_install/#install-no-deps), as per [pip's recommendation](https://pip.pypa.io/en/stable/topics/repeatable-installs/))

### Suggested solution
Remove [setuptools requirement](https://github.com/googleapis/python-api-core/blob/ef6f0fcfdfe771172056e35e3c990998b3b00416/setup.py#L36) from install_requires

### Alternative solutions
For my use, use `pip-tools --allow-unsafe`, or `pip install` without `--no-deps`, but this doesn't solve the underlying issue

### Additional context
Setuptools is only used in the `google-api-core` package during build-time (as the [legacy](https://pip.pypa.io/en/stable/reference/build-system/setup-py/) build backend), and not during runtime (a [repository search](https://github.com/googleapis/python-api-core/search?q=setuptools) confirms this)

Related issues:
* googleapis/google-auth-library-python#595 (resolved by googleapis/google-auth-library-python#913)
* #325

**Comment by busunkim96** [comment]
Thanks @EpicWink, that sounds reasonable. I opened #339 to remove `setuptools` from `install_requires`.
