### ISSUE TITLE
use unittest.mock instead of mock

### ISSUE THREAD

**Issue by pgajdos** [googleapis/python-api-core#377]
Rather a question, do you plan to migrate mock usage in tests to built-in unittest.mock instead?

**Comment by pgajdos** [comment]
The testsuite runs fine for me with Python 3.8, 3.9 and 3.10 with unittest.mock:
https://build.opensuse.org/package/show/home:pgajdos:python/python-google-api-core/
https://build.opensuse.org/package/live_build_log/home:pgajdos:python/python-google-api-core:test/openSUSE_Tumbleweed/x86_64

It seems to be just  `s/import mock/from unittest import mock/`

Backtround:
https://trello.com/c/S6eADbii/64-remove-python-mock
https://fedoraproject.org/wiki/Changes/DeprecatePythonMock

**Comment by parthea** [comment]
Hi @pgajdos,
Thanks for reporting this issue. PRs are welcome!
