### ISSUE TITLE
'grpc.experimental.aio' has no attribute 'StreamUnaryCall' due to PR#29

### ISSUE THREAD

**Issue by gtoonstra** [googleapis/python-api-core#40]
We observe a stack trace on one of our clusters due to a package upgrade, possibly introduced by the new release of python-api-core, which we don't pin to a specific version.

Due to PR#29, we now see the following error:

'grpc.experimental.aio' has no attribute 'StreamUnaryCall'

We will pin our version to the previous one, but documenting this here as it can affect other customers. Probably we should be pinning a more recent version of google.cloud libraries that are compatible, we're still researching this.

#### Environment details

  - OS type and version: image 1.4-ubuntu18 (GCP dataproc).
  - Python version: 3.6
  - pip version: `pip --version`
  - `google-api-core` version: 1.19.0

#### Steps to reproduce

  1. See stack trace below, it happens on import bigquery client.

#### Stack trace
```
    from google.cloud import bigquery, bigquery_storage, storage
  File "/opt/conda/default/lib/python3.6/site-packages/google/cloud/bigquery/__init__.py", line 35, in <module>
    from google.cloud.bigquery.client import Client
  File "/opt/conda/default/lib/python3.6/site-packages/google/cloud/bigquery/client.py", line 58, in <module>
    from google.cloud.bigquery import _pandas_helpers
  File "/opt/conda/default/lib/python3.6/site-packages/google/cloud/bigquery/_pandas_helpers.py", line 25, in <module>
    from google.cloud import bigquery_storage_v1beta1
  File "/opt/conda/default/lib/python3.6/site-packages/google/cloud/bigquery_storage_v1beta1/__init__.py", line 26, in <module>
    from google.cloud.bigquery_storage_v1beta1 import client
  File "/opt/conda/default/lib/python3.6/site-packages/google/cloud/bigquery_storage_v1beta1/client.py", line 24, in <module>
    import google.api_core.gapic_v1.method
  File "/opt/conda/default/lib/python3.6/site-packages/google/api_core/gapic_v1/__init__.py", line 26, in <module>
    from google.api_core.gapic_v1 import method_async  # noqa: F401
  File "/opt/conda/default/lib/python3.6/site-packages/google/api_core/gapic_v1/method_async.py", line 20, in <module>
    from google.api_core import general_helpers, grpc_helpers_async
  File "/opt/conda/default/lib/python3.6/site-packages/google/api_core/grpc_helpers_async.py", line 145, in <module>
    class _WrappedStreamUnaryCall(_WrappedUnaryResponseMixin, _WrappedStreamRequestMixin, aio.StreamUnaryCall):
AttributeError: module 'grpc.experimental.aio' has no attribute 'StreamUnaryCall'
```

**Comment by gtoonstra** [comment]
These are the version numbers of the relevant libraries that we pin down:

        "pandas==1.0.2",
        "google-cloud-bigquery==1.23.0",
        "google-cloud-bigquery-storage==0.7.0",
        "google-cloud-storage==1.23.0",
        "pyarrow==0.15.1",
        "grpcio==1.27.2",

**Comment by KushGoyal** [comment]
I am getting the same error.

As a workaround using as older version.
google-api-core==1.16.0

**Comment by bchazalet** [comment]
we too have been bitten by this in a cloud function. It was painful to track down.

**Comment by fernandobrito** [comment]
I just had a similar issue in our Google Cloud Composer environment.

Requirements:
```
boto3==1.11.17
snowflake-sqlalchemy~=1.2.0
google-cloud-bigquery-datatransfer~=0.4.1
pybigquery~=0.4.15
setuptools~=46.1.3
google-cloud-bigquery==1.24.0
docker==4.2.1
```

Everything was working fine until today when I added the last row and it triggered some versions bumps.

The error manifested to me as: 
```
  File "/home/airflow/gcs/dags/jobs_history/import_jobs_history.py", line 13, in <module>
    from google.cloud import bigquery_datatransfer_v1
  File "/opt/python3.6/lib/python3.6/site-packages/google/cloud/bigquery_datatransfer_v1/__init__.py", line 23, in <module>
    from google.cloud.bigquery_datatransfer_v1.gapic import data_transfer_service_client
  File "/opt/python3.6/lib/python3.6/site-packages/google/cloud/bigquery_datatransfer_v1/gapic/data_transfer_service_client.py", line 25, in <module>
    import google.api_core.gapic_v1.client_info
  File "/opt/python3.6/lib/python3.6/site-packages/google/api_core/gapic_v1/__init__.py", line 26, in <module>
    from google.api_core.gapic_v1 import method_async  # noqa: F401
  File "/opt/python3.6/lib/python3.6/site-packages/google/api_core/gapic_v1/method_async.py", line 20, in <module>
    from google.api_core import general_helpers, grpc_helpers_async
  File "/opt/python3.6/lib/python3.6/site-packages/google/api_core/grpc_helpers_async.py", line 25, in <module>
    from grpc.experimental import aio
ImportError: cannot import name 'aio'
```

The fix was adding `google-api-core==1.17.0` to my requirements. `1.18.0` also causes the same error.

Google Cloud Composer `composer-1.8.4-airflow-1.10.3`
Python `3.6.8`

**Comment by busunkim96** [comment]
Sorry for the trouble this is causing folks! Please continue to use `google-api-core==1.16.0` until this is resolved.

I suspect we need to increase the minimum required ``grpcio`` version. https://github.com/googleapis/python-api-core/blob/master/setup.py#L42 

@lidizheng

**Comment by lidizheng** [comment]
@busunkim96 The minimum version of `grpcio` for the latest release of `google-api-core` is `v1.29.0`. The new release of gRPC Python adds support for retry in AsyncIO, and fix some stability issue.

Sorry that I didn't add this constraint earlier. Here is a PR to bump up the minimum version: https://github.com/googleapis/python-api-core/pull/41

**Comment by busunkim96** [comment]
@lidizheng No worries, It slipped my mind as well. Thank you for the PR!

**Comment by luogantt** [comment]
` pip install google-api-core==1.16` 

solve the problem

**Comment by ZhengxunWu** [comment]
> @busunkim96 The minimum version of `grpcio` for the latest release of `google-api-core` is `v1.29.0`. The new release of gRPC Python adds support for retry in AsyncIO, and fix some stability issue.
> 
> Sorry that I didn't add this constraint earlier. Here is a PR to bump up the minimum version: #41

Hi, but even if I upgraded to `v1.36.1`, still have the same error. Have been trying to fix it for quite a long time.
Relevant packages:
```
google-api-core           1.22.2           py37h21ff451_0
google-auth               1.25.0             pyh44b312d_0    conda-forge
google-cloud-bigquery     1.22.0                   py37_0    conda-forge
google-cloud-bigquery-storage 0.6.0                    py37_0    conda-forge
google-cloud-core         1.3.0                      py_0
google-pasta              0.2.0                      py_0
google-resumable-media    0.5.1              pyh9f0ad1d_0    conda-forge
googleapis-common-protos  1.52.0           py37h2eaa2aa_0
```

**Comment by lidizheng** [comment]
@ZhengxunWu Hi, can you try to upgrade all packages to the latest version and try again? Also, what Python interpretor version did you use?

We tried hard to make sure there isn't any regression when we move gRPC AsyncIO API to stable a year ago. There might be something changed in Python's import mechanism.

**Comment by pramodh941** [comment]
I am facing the same issue. To summarise from the above workaround suggestions:

- pin our version to the previous one (google-api-core==1.16.0), but the current version I have is (google-api-core-1.31.1). I got this error message  {**ImportError: cannot import name 'grpc_helpers_async' from 'google.api_core' (/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/google/api_core/__init__.py)**} when I switched to  (google-api-core==1.16.0) @luogantt

- Alternatively, upgrading to the latest version of grpcio should also resolve the issue, I have this version if I am pointing this correctly: {**grpcio<2.0.0dev,>=1.0.0 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from grpc-google-iam-v1<0.13dev,>=0.12.3->google-cloud-container>=0.3.0->caliban) (1.27.2)**}
- @lidizheng , I am using **Python version 3.8** . Could you help me understand how do I resolve this issue?

Please find attached terminal report
[caliban.pdf](https://github.com/googleapis/python-api-core/files/6912722/caliban.pdf)

**Comment by lidizheng** [comment]
@pramodh941 According to GitHub, the `grpcio` version restriction is only added for `google-api-core>=1.19.1`. And, what you are getting is an old version before the initial asyncio support.

Can I ask if it is possible to use the latest `google-api-core`? If not, what is blocking it?

**Comment by pramodh941** [comment]
@lidizheng yeah, I tried initially with the latest version 1.31.1, but it's not working

**Comment by lidizheng** [comment]
Sorry about that. I saw the import namespace error, as well as the asyncio helper import error. I will take a closer look before EOD.

**Comment by busunkim96** [comment]
@pramodh941 Could you try installing in a brand new virtual environment?

```
python3 -m venv env
source env/bin/activate
pip install caliban
```

In the first bit of the log it looks like an older version of `grpcio` (1.27.2) is being used:

```
Requirement already satisfied: grpcio<2.0.0dev,>=1.0.0 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from grpc-google-iam-v1<0.13dev,>=0.12.3->google
-cloud-container>=0.3.0->caliban) (1.27.2)
```
To be extra sure, you can also check the `grpcio` version used at runtime:
```py
import grpc
print(grpc.__version__)
```

I'm not sure why pip wouldn't upgrade `grpcio==1.27.2` when `google-cloud-container` is installed though.  The latest `google-cloud-container` requires `google-api-core>=1.26.0, <3.0.0dev` which would in turn require a version of `grpcio` (`grpcio >= 1.29.0, < 2.0dev`) with the `grpc.experimental.aio` surface.
