### ISSUE TITLE
Automatically release docs when a new release happens

### ISSUE THREAD

**Issue by nbro10** [googleapis/python-api-core#435]
I've noticed that the latest documentation available here https://googleapis.dev/python/google-api-core/latest/index.html (2.8.2) does not correspond to the currently latest release (2.10.0).

Given that we have some documentation that depends on yours and we'd like to use the latest version of this API, 2.10, is it possible to release the documentation that corresponds to the latest version of the API? Ideally, this release of the documentation should automatically happen in sync with the release of the API, so that this issue does not occur again. 

Thanks!

**Comment by parthea** [comment]
Thanks for reporting this issue. This issue appears to be fixed now.
