### ISSUE TITLE
v1.33.0 - operations_v1/transports/rest.py", line 19 - cannot import name '__version__' from '<unknown module name>' (unknown location)

### ISSUE THREAD

**Issue by mkj28** [googleapis/python-api-core#447]
Seems new in v1.33.0: https://github.com/googleapis/python-api-core/commit/a175ce55578a6a3e79b6960d8e28d4e7f67ce5ee#diff-9355b210dc5d75f42434462f3f0aca13acb3bb9bbf993541d5520cb1ec32aa4e

#### Environment details

  - OS type and version: docker python:3.8-buster
  - Python version: `3.8.10`
  - pip version: `22.2.2`
  - `google-api-core` version: `v1.33.0`

#### Steps to reproduce

  1.  from google.api_core import operations_v1

#### Code example

```python
 from google.api_core import operations_v1
```

#### Stack trace
```
    from google.api_core import operations_v1  # type: ignore
  File "/usr/local/lib/python3.8/site-packages/google/api_core/operations_v1/__init__.py", line 17, in <module>
    from google.api_core.operations_v1.abstract_operations_client import AbstractOperationsClient
  File "/usr/local/lib/python3.8/site-packages/google/api_core/operations_v1/abstract_operations_client.py", line 26, in <module>
    from google.api_core.operations_v1.transports.base import (
  File "/usr/local/lib/python3.8/site-packages/google/api_core/operations_v1/transports/__init__.py", line 20, in <module>
    from .rest import OperationsRestTransport
  File "/usr/local/lib/python3.8/site-packages/google/api_core/operations_v1/transports/rest.py", line 19, in <module>
    from requests import __version__ as requests_version
ImportError: cannot import name '__version__' from '<unknown module name>' (unknown location)

```

**Comment by parthea** [comment]
Hello @mkj28, 
`[requests](https://github.com/googleapis/python-api-core/blob/v1/setup.py#L35)` is a required dependency of this library. From the stack trace, it appears that the `requests` package is not installed. Please can you confirm that the environment where the code was run is the same environment where `google-api-core` was installed? Please can you also share the output of `pip freeze`?

**Comment by mkj28** [comment]
Hmm good point, I don't see anything removing requests on our side, but let's close this for now, needs more investigation on my side.

**Comment by mkj28** [comment]
OK just to close it out - issue was on our side, we were mocking requests, which now that the library is pulled in, was breaking the tests.

Fix was to remove `sys.modules["requests"] = MagicMock()`
