### ISSUE TITLE
missing 'proto' module

### ISSUE THREAD

**Issue by 0-wiz-0** [googleapis/python-api-core#448]
#### Environment details

  - OS type and version: NetBSD-9.99.99/amd64
  - Python version: python 3.10.7
  - pip version: pip 22.2.2
  - `google-api-core` version: 2.10.1

#### Steps to reproduce

I'm trying to run the self tests using the pypi distfile and running 'pytest'.
I see:
```
___________________________________ ERROR collecting tests/unit/test_rest_streaming.py ___________________________________
ImportError while importing test module '/scratch/devel/py-google-api-core/work/google-api-core-2.10.1/tests/unit/test_res
t_streaming.py'.                                                                                                          
Hint: make sure your test modules/packages have valid Python names.                                                       
Traceback:                                                                                                                
/usr/pkg/lib/python3.10/importlib/__init__.py:126: in import_module                                                       
    return _bootstrap._gcd_import(name[level:], package, level)                                                           
tests/unit/test_rest_streaming.py:22: in <module>                                                                         
    import proto                                                                                                          
E   ModuleNotFoundError: No module named 'proto'                                                                          
```
and pytest fails collecting the tests.

Where is the proto module supposed to come from?

When I manually remove the test file, pytest runs to completion with
```
7 failed, 559 passed, 71 skipped, 138 warnings
```

**Comment by vam-google** [comment]
Hi @0-wiz-0,
The proto module is https://pypi.org/project/proto-plus/ (https://github.com/googleapis/proto-plus-python).
The tests are supposed to be ran via [nox](https://nox.thea.codes/en/stable/) tool. If you want to run it directly via pytest, then just install proto plus in your env first.

On the other hand, I guess it is an issue, that tests depend on something, which is not defined in setup, plus proto-plus itself depends on api-core, so making api-core depend on proto-plus would make it a circular dependency. But given that these are tests only, I believe leaving it as is ok.

**Comment by 0-wiz-0** [comment]
Thanks for the pointer, adding proto-plus to the environment fixed the issue.

The dependencies are currently listed in `setup.py`, I think it'd be good to also list the test dependencies there.

Having a cyclic dependency is, of course, not a good idea and would be a problem. I see that proto-plus lists google-api-core in `setup.py`, but I don't see where it's actually used?
