### ISSUE TITLE
max_tries argument for retries

### ISSUE THREAD

**Issue by daniel-sanche** [googleapis/python-api-core#531]
Currently, retries only expire due to time-based timeout. In some cases, it is useful to have an attempt-based expiration option (for example, for datastore). 

We could add a max_tries argument to our retry functions, and set it to None by default. But allow users to override it

This feature would have implications for https://github.com/googleapis/python-api-core/issues/530, which would have to expose an additional failure reason instead of the bool `is_timeout`

**Comment by ohmayr** [comment]
Closing this since we have the following issue: https://github.com/googleapis/python-api-core/issues/535
