### ISSUE TITLE
fix exception handling: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by vchudnov-g** [googleapis/python-api-core#578]
While debugging another issue, I got the error message 
```
File "[REDACTED]/google/api_core/exceptions.py", line 495, in from_http_response
    filter(
TypeError: 'NoneType' object is not iterable
```

The offending code is this: https://github.com/googleapis/python-api-core/blob/17ff5f1d83a9a6f50a0226fb0e794634bd584f17/google/api_core/exceptions.py#L495-L499

**Comment by vchudnov-g** [comment]
Should be a trivial fix, but I don't want to context switch yet.

**Comment by parthea** [comment]
Closing as there is no code to reproduce the issue
