### ISSUE TITLE
AttributeError: module 'grpc.experimental.aio' has no attribute 'StreamUnaryCall'

### ISSUE THREAD

**Issue by sravanvemi1995** [googleapis/python-api-core#72]
I am using Google Document AI cloud service API and i am facing the issue and struck with the error 

AttributeError: module 'grpc.experimental.aio' has no attribute 'StreamUnaryCall'

#### Environment details

google-api-core==1.22.1
google-auth==1.20.1
google-cloud==0.34.0
google-cloud-documentai==0.2.0
google-cloud-vision==1.0.0
googleapis-common-protos==1.52.0
grpcio==1.31.0

#### Code example

```
pip install google-cloud
pip install google-cloud-documentai
from google.cloud import documentai_v1beta2 
```

Thanks!

**Comment by busunkim96** [comment]
Hi - 

You don't need to install `google-cloud`. It is a deprecated package that has been replaced with the `google-cloud-*` packages.

Can you try installing just `google-cloud-documentai` in a new virtualenv?

```
python3 -m venv env
source env/bin/activate
pip install google-cloud-documentai
```
