### ISSUE TITLE
Streams with prefecth_first_result do not convert grpc errors

### ISSUE THREAD

**Issue by daniel-sanche** [googleapis/python-api-core#731]
one task of grpc_helpers is to wrap grpc channels in `error_remapped_callable`, converting grpc errors into `api_core.exception` types. But this error remapping is skipped when processing a streaming rpc with [prefetch_first](https://github.com/googleapis/python-api-core/blob/2100f7869d9dc4b75c594c95c51e4db8c392834f/google/api_core/grpc_helpers.py#L169) enabled.

When prefetch_first is enabled, the StreamingResponseIterator [calls next as part of its init](https://github.com/googleapis/python-api-core/blob/2100f7869d9dc4b75c594c95c51e4db8c392834f/google/api_core/grpc_helpers.py#L92). But if there is an error as part of the next call, the grpc error is raised immediately, without being wrapped

Because the error is not wrapped, and it is raised outside the usual call loop, this will cause retryable errors to not be retried properly

---

To solve this, we should probably [add a case to this try/catch](https://github.com/googleapis/python-api-core/blob/2100f7869d9dc4b75c594c95c51e4db8c392834f/google/api_core/grpc_helpers.py#L92):
```
       except grpc.RpcError as exc:
            self._stored_first_result = exc
```

And then raise it as part of \_\_next\_\_ [if present here](https://github.com/googleapis/python-api-core/blob/2100f7869d9dc4b75c594c95c51e4db8c392834f/google/api_core/grpc_helpers.py#L112)

related: b/368027810

**Comment by daniel-sanche** [comment]
Actually, looking closer, the exception should be handled up higher in the stack by [this catch](https://github.com/googleapis/python-api-core/blob/0708409bdeee10ff60485dab831bf0a258652e20/google/api_core/grpc_helpers.py#L186). It's not clear why we're seeing the errors we see in  b/368027810

**Comment by parthea** [comment]
Closing due to https://github.com/googleapis/python-api-core/issues/731#issuecomment-2403513344. Please re-open if there is still an issue
